"""empty message

Revision ID: 0209e7eb09ee
Revises: 2646a3c70635
Create Date: 2024-09-01 21:20:04.812159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0209e7eb09ee'
down_revision = '2646a3c70635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', postgresql.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer_Details', schema=None) as batch_op:
        batch_op.drop_column('cart')

    # ### end Alembic commands ###
